version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a NSwag.zip %APPVEYOR_BUILD_FOLDER%\NSwag\bin\Release\net8.0\*.*

    appveyor PushArtifact NSwag.zip
deploy:
- provider: GitHub
  release: NSwag-v$(APPVEYOR_BUILD_VERSION)
  description: Release description
  auth_token:
    secure: BJFiPQhbi4Q9jbg6AYqI4Gy2W6B61y2tH9ggn2Jrj/c/yURY8dAmb9ULlkyTejQW
  artifact: /.*\.zip/
  on:
    branch: master
