version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a NSwag.zip %APPVEYOR_BUILD_FOLDER%\NSwag\bin\Release\*.*

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.CoreUtility.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.Language.Intellisense.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.Language.Intellisense.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.Text.Data.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.Text.Logic.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.Text.UI.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.Text.UI.Wpf.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.Validation.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\Microsoft.VisualStudio.Language.dll

    del %APPVEYOR_BUILD_FOLDER%\MyOpCodesExtension\bin\Release\StreamJsonRpc.dll

    appveyor PushArtifact NSwag.zip
deploy:
- provider: GitHub
  release: NSwag-v$(APPVEYOR_BUILD_VERSION)
  description: Release description
  auth_token:
    secure: BJFiPQhbi4Q9jbg6AYqI4Gy2W6B61y2tH9ggn2Jrj/c/yURY8dAmb9ULlkyTejQW
  artifact: /.*\.zip/
  on:
    branch: master