version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a NSwag.zip %APPVEYOR_BUILD_FOLDER%\src\NSwag\bin\Release\net9.0\*.*

    appveyor PushArtifact NSwag.zip
deploy:
- provider: GitHub
  release: NSwag-v$(APPVEYOR_BUILD_VERSION)
  description: Release description
  auth_token:
    secure: 5ZaT9wKNoENOi2va55xzYo5MQyHlqRyQr71DFBw6A7ovfj0CBwa20gQrl13IjbqX
  artifact: /.*\.zip/
  on:
    branch: master
