version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a NSwag.zip %APPVEYOR_BUILD_FOLDER%\src\NSwag\bin\Release\net8.0\*.*

    appveyor PushArtifact NSwag.zip
deploy:
- provider: GitHub
  release: NSwag-v$(APPVEYOR_BUILD_VERSION)
  description: Release description
  auth_token:
    secure: sGvXHW8/VMYpZ9+X7/KMOGnYRnA+Opj0/wK20UjJZbFtDP22dxRsC7C+M44h702u
  artifact: /.*\.zip/
  on:
    branch: master
